### PR TITLE
project-requests | adding Winston

### PR DESCRIPTION
**Pull request by dreamingrainbow**
# ApeSwap Liquidity Health Config Submission

_Before creating a pull request, please make sure read our [instructions](https://github.com/ApeSwapFinance/lhd-config#how-to-submit-a-change)!_

**Project Details:**

```
Project Name: Winston
Discord: https://discord.gg/rickle-897546129108008960
Project Manager: @dreamingrainbow#0
```

**Contact Information:**
Michael Dennis admin@winston.services AKA @dreamingrainbow $dreamingrainbow #Free2CodeIt
```
Point of Contact Telegram:
Did you add @liquiditymonkey as a contact on Telegram?: No don't use telegram.
Did you send a message to the Liquidity Monkey?: No, again don't use telegram, we are on Discord. Reach out anytime.
```

**Additional Details (Optional):**
Winston is your personal assistant to all things blockchain. Winston token is used to reward members and used to help teach the public about the various uses, processes, and programs available in decentralized finance. We are a learn to earn platform that's core mission is to help bring decentralized finance to the common person. You can check out more details about our project on our github profile, or read the back story in our Discord.
https://github.com/Winston-Services/docs
Find us in Discord, and join our wonderful community. https://discord.gg/rickle-897546129108008960
```
Proof of ownership addresses (docs links, on-chain info, etc):
Ownership of the contract was released to the contract itself.
Created by : 0xF9B9eE3B0301B511cd5AA4b8D039F63df19C615a
https://github.com/Winston-Services/docs
https://bscscan.com/address/0x75578ebbefe274f240b8e1b5859ca34f342157d9
Primary Organization Wallet :  0xF9B9eE3B0301B511cd5AA4b8D039F63df19C615a

Anything else?:
We look forward to a bright future in DeFi, in our second year now we are setting new heights to reach our core mission. We aim to help the common person learn to earn with decentralized finance and look forward to another year of using ApeSwap Finance to help us reach and teach people about blockchain technology.
```

### CODE REVIEW

**Comment by VandeurenGlenn** [comment]
Heads up @dreamingrainbow  is a fraud, he talks allot but does nothing and has nothing to offer beware of Rickle and Winston.

**Comment by VandeurenGlenn** [comment]
> > Heads up @dreamingrainbow is a fraud, he talks allot but does nothing and has nothing to offer beware of Rickle and Winston.
> 
> Your an idiot, @VandeurenGlenn you are going around spreading fud about me. You have nothing. Continue this harassment so that the world can see what kinda of nonsense you make up. My history and reputation speak for themselves. You however are only showing that your not worth anyone's time..

You what now? You can't access your desktop because your place is full of filth? What history and what reputation? You may had credibility in the past but you lost it selling tokens to pay your electricity bill plus the noncence you tell plus in like you said yourself multiple times that you lazy.
I mean goddamn Michael on day you be like your the best programmer around and the next day your crying and suddenly calls yourself a bad programmer so ....
Ps look at my GitHub and then look at yours, that's nonsense I made up? Me actually coding you doing what ?...
You can live in your Dreamworld as long as you want but nobody is joining.

But please do report me, let's see who's gonna get removed, the guy telling people he does something but doesn't have something to show or me actually doing something and allot to show.

Be careful who your calls an idiot.

**Comment by VandeurenGlenn** [comment]
Anyways @dreamingrainbow I wanted to resolve this in private. So it's up to you.

**Comment by Yogzcollectd** [comment]
🤔🤔

**Pull request closed without merging**
